-- liquibase formatted sql

-- changeset burda:1786871957146-1
CREATE TABLE public.users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(32)                             NOT NULL,
    name  VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
ALTER TABLE public.users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

-- changeset burda:1786871957067-1
CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

-- changeset burda:1786871957067-2
CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id)
);

-- changeset burda:1786871957067-3
CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

-- changeset burda:1786871957067-4
CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(255)                            NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    confirmed_requests INTEGER,
    created_on         TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    description        VARCHAR(255)                            NOT NULL,
    event_date         TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    published_on       TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    request_moderation BOOLEAN,
    state              VARCHAR(255)                            NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    views              BIGINT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

-- changeset burda:1786871957067-5
CREATE TABLE locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

-- changeset burda:1786871957067-6
ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

-- changeset burda:1786871957067-7
ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

-- changeset burda:1786871957067-8
ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES public.users (id);

-- changeset burda:1786871957067-9
ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_LOCATION FOREIGN KEY (location_id) REFERENCES locations (id);

-- changeset burda:1786871957067-10
ALTER TABLE compilation_events
    ADD CONSTRAINT fk_comeve_on_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id);

-- changeset burda:1786871957067-11
ALTER TABLE compilation_events
    ADD CONSTRAINT fk_comeve_on_event FOREIGN KEY (event_id) REFERENCES events (id);

