-- liquibase formatted sql

-- changeset Andrey_Burdak:1787034454903-1
CREATE TABLE requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id     BIGINT,
    created      TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    requester_id BIGINT,
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);

-- changeset Andrey_Burdak:1787034454903-2
ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

-- changeset Andrey_Burdak:1787034454903-3
ALTER TABLE requests
    ADD CONSTRAINT FK_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES public.users (id);

