-- liquibase formatted sql

-- changeset Andrey_Burdak:1787333765032-1
CREATE TABLE admin_locations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name   VARCHAR(255)                            NOT NULL,
    lat    FLOAT                                   NOT NULL,
    lon    FLOAT                                   NOT NULL,
    radius DOUBLE PRECISION                        NOT NULL,

    CONSTRAINT pk_admin_locations PRIMARY KEY (id),
    CONSTRAINT uc_admin_locations_name UNIQUE (name),


    CONSTRAINT chk_admin_locations_lat
        CHECK ( lat >= -90 AND lat <= 90),

    CONSTRAINT chk_admin_location_lon
        CHECK ( lon >= -180 AND lat <= 90),

    CONSTRAINT chk_admin_locations_radius
        CHECK ( radius > 0)
);
