-- liquibase formatted sql

-- changeset Andrey_Burdak:1787238871785-1
CREATE TABLE apps
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(32)                             NOT NULL,
    CONSTRAINT pk_apps PRIMARY KEY (id)
);

-- changeset Andrey_Burdak:1787238871785-2
CREATE TABLE hits
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id        BIGINT                                  NOT NULL,
    uri           VARCHAR(512)                            NOT NULL,
    ip            VARCHAR(64)                             NOT NULL,
    hit_timestamp TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);

-- changeset Andrey_Burdak:1787238871785-3
ALTER TABLE apps
    ADD CONSTRAINT uc_apps_name UNIQUE (name);

-- changeset Andrey_Burdak:1787238871785-4
ALTER TABLE hits
    ADD CONSTRAINT FK_HITS_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id);

